name: My First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: printing the statement1
        run: echo "Hello GitHub Actions!"
      - name: printing the statement2
        run: echo "My First Workflow"
